MACHINE_EXTRA_RDEPENDS += " \
			   opkg	\
                           gdb \
			   cgdb \
			   jansson \
			   sqlite3 \
			   zlib \ 
			   gnutls \
			   python3 \
			   python \
			   ncurses \
			   openssl \
			   ca-certificates \
			   cryptsetup \
			   tcpdump \
			   curl \
			   wget \
			   rpm \
			   json-c \
			   log4c \
			   ntp \
                           "
IMAGE_FEATURES += "ssh-server-openssh"
